Dockerfile: downgrade coreutils due to nfs acl errors
This should fix following errors on our build servers:

   DEBUG: Executing python function do_unpack
   NOTE: Freescale EULA has been accepted for 'imx-boot-firmware-files'
   DEBUG: Executing python function base_do_unpack
   NOTE: Unpacking [...]/out-schsm/downloads/firmware-imx-8.26.1-410be01.bin to \
         [...]/out-schsm/tmp/work/cortexa53-crypto-imx-gyroidos-linux-musl/imx-boot-firmware-files/8.26.1/
   cp: preserving permissions for ‘./firmware-imx-8.26.1-410be01.bin’: Operation not supported
   ERROR: Bitbake Fetcher Error: UnpackError[...]

Signed-off-by: Michael Weiß <michael.weiss@aisec.fraunhofer.de>